package hu.bakro.test1;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TiliToli
//  @ File Name : Item.java
//  @ Date : 2014.05.04.
//  @ Author : Bakró Nagy István
//
//

public class Item {
	private int _x;
	private int _y;
	
	public Item(int x, int y) {
		_x = x;
		_y = y;
	}
	
	public int getX() {
		return _x;
	}
	
	public int getY() {
		return _y;
	}
	
	/**
	 * Megnezi, hogy az aktualis pozicioja megegyezik a konstrukcioja soran megadottakkal.
	 *
	 * @param    x
	 * @param    y
	**/
	public boolean isInGoodPlace(int x, int y) {
		return (_x == x) && (_y == y);
	}
}
