package hu.bakro.test1;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JLabel;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TiliToli
//  @ File Name : Stopwatch.java
//  @ Date : 2014.05.06.
//  @ Author : Bakró Nagy István
//
//
import javax.swing.Timer;

public class StopWatch extends JLabel implements ActionListener {
	private int _h;
	private int _m;
	private int _s;
	private int _ms;
	
	private boolean _running = false;
	private Timer _alarm;
	
	public StopWatch() {
		super( "0:0:0.0", JLabel.CENTER );
		_alarm = new Timer( 10, this);
	}
	
	/**
	 * A stopperora akutalis erteke sting-kent
	**/
	public String getTime() {
		return Integer.toString(_h) + ":" + 
				Integer.toString(_m) + ":" +
				Integer.toString(_s) + "." + 
				Integer.toString(_ms) ;
	}
	
	/**
	 * Idozito eventjenek kezelese: a stopperora ertekenek leptetese
	 *
	 * @param    ev
	**/
	public void actionPerformed(ActionEvent ev) {
		if (_running) {
		    _ms++;
		    if(_ms == 100) {
		    	_ms = 0;
		    	_s++;
	
				if(_s == 60) {
				    _s = 0;
				    _m++;
	
				    if(_m == 60) {
				    	_m = 0;
				    	_h++;
				    }
				}
		    }
		    
		    update();
		}
		_alarm.restart();
	}
	
	/**
	 * Stopperora visszaallitasa
	**/
	public void reset() {
		_alarm.stop();

		_h = 0;
		_m = 0;
		_s = 0;
		_ms = 0;
		
		update();
		_running = false;
		
		_alarm.restart();
	}
	
	/**
	 * Stopperora elinditasa
	**/
	public void start() {
		_running = true;
		_alarm.start();
	}
	
	/**
	 * Stopperora megallitasa
	**/
	public void stop() {
		_running = false;
		_alarm.stop();
	}
	
	/**
	 * Cimke frissitese
	**/
	public void update() {
		setText( Integer.toString(_h) + ":" + 
				 Integer.toString(_m) + ":" +
				 Integer.toString(_s) + "." + 
				 Integer.toString(_ms) );
	}
}
