package hu.bakro.test1;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TiliToli
//  @ File Name : SurfacePanel.java
//  @ Date : 2014.05.04.
//  @ Author : Bakró Nagy István
//
//

public class SurfacePanel extends JPanel implements MouseListener {
	private final int _xNum;
	private final int _yNum;
	private final int _sidePixels;
	private ToliCore _core;
	
	public SurfacePanel(ToliCore core, int xNum, int yNum, int sidePixels) {
		_xNum = xNum;
		_yNum = yNum;
		_sidePixels = sidePixels;
		_core = core;
		
        this.setPreferredSize(new Dimension(_sidePixels * _xNum, _sidePixels * _yNum));
        this.setBackground(Color.white);
        this.addMouseListener(this);
	}
	
	public void paintComponent(Graphics g) {
		super.paintComponent(g);
		for(int xx = 0; xx < _xNum; xx++) {
			for(int yy = 0; yy < _yNum; yy++) {
				Item it = _core.getItem(xx, yy);
				// nem ures elemek rajzolasa
                if(it != null) {
                	String str = Integer.toString((it._x * _yNum) + it._y);
                	
                    g.setColor(Color.lightGray);
                    g.fillRect((yy*_sidePixels)+1, (xx*_sidePixels)+1, _sidePixels-2, _sidePixels-2);
                    g.setColor(Color.black);
                    g.drawString(str, (int)((yy+0.5)*_sidePixels), (int)((xx+0.5)*_sidePixels));
                }
            }
        }
	}
	
	/**
	 * Kattintas elkapasa es az elem-re a move meghivasa.
	 *
	 * @param    e
	**/
	public void mousePressed(MouseEvent e) {
		if(_core.isInProgress()) {
			//System.out.println(e.toString());
			// kattintas relativ koordinatainak elem-indexe alakitasa
	        int xToMove = e.getY() / _sidePixels;
	        int yToMove = e.getX() / _sidePixels;
	        
	        // kattintott elem mozgatasa
	        _core.move(xToMove, yToMove);
	        
	        this.repaint();
	        
	        // vizsgalat hogy vege a jateknak
	        if(_core.isGameOver()) {
	        	JOptionPane.showMessageDialog(null, "Gyõztél!", "Gratulálok, Gyõztél!", JOptionPane.INFORMATION_MESSAGE);
	        	
	        }
		}
        
	}
	/*
	 * muszaj implementalni, de eldobjuk
	 */
	public void mouseClicked(MouseEvent e) {
	}
	
	public void mouseReleased(MouseEvent e) {
	}
	
	public void mouseEntered(MouseEvent e) {
	}
	
	public void mouseExited(MouseEvent e) {
	}
}
