package hu.bakro.test1;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JPanel;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TiliToli
//  @ File Name : ToliGui.java
//  @ Date : 2014.05.04.
//  @ Author : Bakró Nagy István
//
//

public class ToliGui extends JPanel {
	private static final int xNum = 3;
	private static final int yNum = 3;
	private static final int sidePixels = 100;
	private ToliCore _core;
	private SurfacePanel _surface;
	
	public ToliGui() {
		_core = new ToliCore(xNum, yNum);
		_surface = new SurfacePanel(_core, xNum, yNum, sidePixels);
		
		//--- Create a button.  Add a listener to it.
        JButton newGameButton = new JButton("New Game");
        newGameButton.addActionListener(new StartGameAction());

        //--- Create control panel
        JPanel controlPanel = new JPanel();
        controlPanel.setLayout(new FlowLayout());
        controlPanel.add(newGameButton);
                
        //--- Set the layout and add the components
        this.setLayout(new BorderLayout());
        this.add(controlPanel, BorderLayout.NORTH);
        this.add(_surface, BorderLayout.CENTER);
	}
	
	
	public class StartGameAction implements ActionListener {
		/**
		 * Gomb lenyomasanak elkapasa es a jatek ujrakezdese.
		 *
		 * @param    e
		**/
		public void actionPerformed(ActionEvent e) {
			_core.shuffle();
			_surface.repaint();
		}
	}
	
}
