package hu.bakro.test1;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

import javax.swing.JButton;
import javax.swing.JPanel;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TiliToli
//  @ File Name : ToliGui.java
//  @ Date : 2014.05.04.
//  @ Author : Bakró Nagy István
//
//

public class ToliGui extends JPanel {
	private static final int sidePixels = 100;
	private final ToliCore _core;
	private final SurfacePanel _surface;
	protected final StopWatch _watch;
	private String _type;
	
	public ToliGui(String type, int xNum, int yNum) {
        // stopperora cimke
        _watch = new StopWatch();
        _type = type;
        
		_core = new ToliCore(xNum, yNum);
		_surface = new SurfacePanel(_type, _core, _watch, xNum, yNum, sidePixels);
		
		// halozati szal letrehozasa
		try {
			if(type.contentEquals("slave")) {
				Thread t = new Server(4242, _core, _surface, this);
				t.start();
			}
		} catch(IOException e) {
			e.printStackTrace();
		}
		
		// jatek elkezdese/ujrakezdese gomb
        JButton newGameButton = new JButton("New Game");
        newGameButton.addActionListener(new StartGameAction());

        // panel
        JPanel controlPanel = new JPanel();
        controlPanel.setLayout(new FlowLayout());
        controlPanel.add(newGameButton);
        controlPanel.add(_watch);
                
        // panelhez az elemez hozzadasa
        this.setLayout(new BorderLayout());
        this.add(controlPanel, BorderLayout.NORTH);
        this.add(_surface, BorderLayout.CENTER);
	}
	
	
	public class StartGameAction implements ActionListener {
		/**
		 * Gomb lenyomasanak elkapasa es a jatek (ujra)kezdese.
		 *
		 * @param    e
		**/
		public void actionPerformed(ActionEvent e) {
			// tabla megkevetese
			_core.shuffle();
			
			// stopperora visszaallitasa es elinditasa
			_watch.reset();
			_watch.start();
			
			// rajzoltatas
			_surface.repaint();
			
			// tavoli peldany allasanak incializalasa
			if(_type.contentEquals("master")) {
				_surface.start();
			}
		}
	}
	
}
